"""
Log cleanup utility.
Cleans up old log files generated by IIS or the application.
"""
import os
import time
import logging

def cleanup_old_logs(logs_dir: str, max_age_days: int = 14) -> dict:
    """
    Deletes files in the specified logs directory older than max_age_days.
    """
    if not os.path.isdir(logs_dir):
        return {"status": "skip", "reason": f"Logs directory does not exist: {logs_dir}"}

    now = time.time()
    max_age_seconds = max_age_days * 86400
    deleted_count = 0
    deleted_bytes = 0

    for filename in os.listdir(logs_dir):
        filepath = os.path.join(logs_dir, filename)
        if not os.path.isfile(filepath):
            continue

        # Use modification time to check age
        file_stat = os.stat(filepath)
        file_age = now - file_stat.st_mtime

        if file_age > max_age_seconds:
            try:
                os.remove(filepath)
                deleted_count += 1
                deleted_bytes += file_stat.st_size
                logging.info(f"Log cleanup: deleted {filename} (age: {file_age / 86400:.1f} days)")
            except OSError as e:
                # File might be in use by IIS
                logging.warning(f"Log cleanup: failed to delete {filename}: {e}")

    return {
        "status": "done",
        "deleted_count": deleted_count,
        "deleted_bytes": deleted_bytes,
    }
